Attempt to display the results of the tests in Github
An attempt to display the test results in github rather than the output
window of the action.

This is a three part process.

1) Download the 'gotestsum' go packages onto the test runner
2) Execute 'gotestsum' to run the tests but write the test results to a
JUnit XML test format file.
3) Use the `test-reporter` community provided github action to display
the results, reading form the JUnit XML file that was previously generated.

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -25,3 +25,18 @@ jobs:
 
       - name: Test Step
         run: go test -v ./...
+
+      - name: Get gotestsum tooling
+        run: go get gotest.tools/gotestsum
+
+      - name: Run gotestsum to generate JUnit XML file
+        run: gotestsum --junitfile unit-tests.xml
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Go Tests            # Name of the check run which will be created
+          path: ./unit-tests.xml    # Path to test results
+          reporter: java-junit        # Format of test results
+          
